edition = "2021"

reorder_imports = true
reorder_modules = true

# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
# imports_layout = "HorizontalVertical"
# reorder_impl_items = true
